# Generated by Django 3.2 on 2022-11-11 06:11

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='the_json',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='work',
            name='the_json',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
